version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: symfony
    php:
        build: ./php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
            - ./nginx/symfony.conf:/etc/nginx/conf.d/symfony.conf
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash:cached
            - ./elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - php
            - nginx
    queue:
      image: rabbitmq:3.6-management-alpine
      environment:
        RABBITMQ_DEFAULT_USER: symfony
        RABBITMQ_DEFAULT_PASS: symfony
      ports:
        - 15672:15672

    mongodb:
      image: mongo
      restart: always
      volumes:
        - ./data/db/mongo:/data/db
      ports:
                - "27020:27017"
      command: --storageEngine wiredTiger

    elasticsearch:
      build:
        context: elasticsearch/
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - elk

networks:
  elk:
    driver: bridge
